# Site settings
title: HEYBUYMYSHIT.COM
description: >
  personal concert merchandise collection, all for sale
baseurl:
url:

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

band_list:
  - "'WEIRD AL' YANKOVIC"
  - "...AND YOU WILL KNOW US BY THE TRAIL OF DEAD"
  - "A PERFECT CIRCLE"
  - "A PLACE TO BURY STRANGERS"
  - "A SILVER MT. ZION"
  - "ABOVE & BEYOND"
  - "AC/DC"
  - "AGENT ORANGE"
  - "AIR"
  - "ALGIERS"
  - "ALICE COOPER"
  - "ALICE IN CHAINS"
  - "ALLMAN BROTHERS BAND"
  - "AMANDA PALMER"
  - "AMANDA PALMER AND THE GRAND THEFT ORCHESTRA"
  - "AMON AMARTH"
  - "AMON TOBIN"
  - "ANDREW W.K."
  - "ANIMAL COLLECTIVE"
  - "ANTEMASQUE"
  - "ANTHRAX"
  - "ANTONY AND THE JOHNSONS"
  - "ANVIL"
  - "APOCALYPTICA"
  - "ARCADE FIRE"
  - "AT THE DRIVE-IN"
  - "AUTOLUX"
  - "AVENGED SEVENFOLD"
  - "BAND OF HORSES"
  - "BARENAKED LADIES"
  - "BARONESS"
  - "BELLE & SEBASTIAN"
  - "BEN FOLDS"
  - "BENT KNEE"
  - "BERT KREISCHER"
  - "BIAFRA FIVE-O"
  - "BIG BAD VOODOO DADDY"
  - "BLACK LIGHT BURNS"
  - "BLACKFIELD"
  - "BLOC PARTY"
  - "BLUE MAN GROUP"
  - "BON IVER"
  - "BOSNIAN RAINBOWS (OMAR RODRIGUEZ-LOPEZ GROUP)"
  - "BRIGHT EYES"
  - "BROKEN BELLS"
  - "BROKEN LIZARD (OF SUPER TROOPERS FAME)"
  - "BUILT TO SPILL"
  - "BUSH"
  - "BUTTHOLE SURFERS"
  - "BUZZCOCKS"
  - "BÉLA FLECK & THE FLECKTONES"
  - "CAKE"
  - "CARAVAN PALACE"
  - "CARINA ROUND"
  - "CARLA BOZULICH"
  - "CARPENTER BRUT"
  - "CAT POWER"
  - "CHELSEA WOLFE"
  - "CHEVELLE"
  - "CINQUANTA: 50 YEARS OF MAYNARD JAMES KEENAN"
  - "CIRCLE"
  - "CLIPPING."
  - "CLOUD NOTHINGS"
  - "COHEED AND CAMBRIA"
  - "COLLECTIVE SOUL"
  - "COMBICHRIST"
  - "CONVERGE"
  - "DANZIG"
  - "DATAROCK"
  - "DAVID BYRNE + ST. VINCENT"
  - "DEADMAU5"
  - "DEATH"
  - "DEFTONES"
  - "DETHKLOK"
  - "DEVIN TOWNSEND"
  - "DEVIN TOWNSEND PROJECT"
  - "DEVO"
  - "DEVOTCHKA"
  - "DIE ROTEN PUNKTE"
  - "DITA VON TEESE"
  - "DRAGONFORCE"
  - "DREAM THEATER"
  - "DREDG"
  - "DROPKICK MURPHYS"
  - "DWARVES"
  - "EARTH WIND & FIRE"
  - "ECHO & THE BUNNYMEN"
  - "EDDIE IZZARD"
  - "ELECTRIC SIX"
  - "EVELYN EVELYN"
  - "FAILURE"
  - "FAITH NO MORE"
  - "FESTIVAL OF THE GOLDEN GATE"
  - "FEVER RAY"
  - "FFS (FRANZ FERDINAND + SPARKS)"
  - "FILTER"
  - "FLIGHT OF THE CONCHORDS"
  - "FLOGGING MOLLY"
  - "FLORENCE + THE MACHINE"
  - "FOO FIGHTERS"
  - "FRANZ FERDINAND"
  - "FRONT LINE ASSEMBLY"
  - "FU MANCHU"
  - "FUCK BUTTONS"
  - "FUCKED UP"
  - "FUN."
  - "FUTURE OF THE LEFT"
  - "GAME OF THRONES"
  - "GENERATION AXE"
  - "GHOST"
  - "GIGANTOUR"
  - "GLEN HANSARD (THE SWELL SEASON / THE FRAMES)"
  - "GODSPEED YOU! BLACK EMPEROR"
  - "GOGOL BORDELLO"
  - "GREEN DAY"
  - "GWAR"
  - "HAMILTON: AN AMERICAN MUSICAL"
  - "HARD X MOUTH TAPED SHUT (THE GIRL WITH THE DRAGON TATTOO)"
  - "HENRY ROLLINS"
  - "HOT CHIP"
  - "HOW TO DESTROY ANGELS"
  - "HYDE"
  - "I'M FROM BARCELONA"
  - "IGGY POP AND THE STOOGES"
  - "IN FLAMES"
  - "INFECTED MUSHROOM"
  - "INTRONAUT"
  - "IRON MAIDEN"
  - "JACKALOPE"
  - "JAKE SHIMABUKURO"
  - "JAPANDROIDS"
  - "JASON WEBLEY"
  - "JEAN-MICHEL JARRE"
  - "JOE SATRIANI"
  - "JOHN 5 & THE CREATURES"
  - "JOHN CARPENTER"
  - "JONATHAN COULTON"
  - "JUDGMENT DAY"
  - "JUSTICE"
  - "JÓNSI (SIGUR RÓS)"
  - "KAMASI WASHINGTON"
  - "KEANE"
  - "KELE (OF BLOC PARTY) + DOES IT OFFEND YOU YEAH? + INNERPARTYSYSTEM"
  - "KILLING JOKE"
  - "KILLSWITCH ENGAGE"
  - "KIMBRA"
  - "KMFDM"
  - "KNEEDELUS (KNEEBODY + DAEDELUS)"
  - "LA PHILHARMONIC"
  - "LADYTRON"
  - "LAIBACH"
  - "LEONARD COHEN"
  - "LIARS"
  - "LITURGY"
  - "LIVE"
  - "LOREENA MCKENNITT"
  - "LOW"
  - "M. WARD"
  - "MAC SABBATH"
  - "MAD NOISE"
  - "MAGMA"
  - "MAN MAN"
  - "MARCY PLAYGROUND"
  - "MARKETA IRGLOVA"
  - "MASSIVE ATTACK"
  - "MASTODON"
  - "MATISYAHU"
  - "MATMOS"
  - "MAYNARD JAMES KEENAN"
  - "MC CHRIS"
  - "MC LARS"
  - "MEGADETH"
  - "MELVINS"
  - "METALLIANCE"
  - "MGMT"
  - "MILLENCOLIN"
  - "MINIBOSSES"
  - "MINISTRY"
  - "MINISTRY / REVOLTING COCKS"
  - "MINUS THE BEAR"
  - "MODEST MOUSE"
  - "MOGWAI"
  - "MORBID ANGEL / BEHEMOTH / KRISIUN / DESPISED ICON"
  - "MURDER BY DEATH"
  - "MUSE"
  - "MUTE MATH"
  - "MY LIFE WITH THE THRILL KILL KULT"
  - "NEIL GAIMAN & AMANDA PALMER"
  - "NEUTRAL MILK HOTEL"
  - "NICKEL CREEK"
  - "NIGHTWISH"
  - "NINE INCH NAILS"
  - "NITZER EBB"
  - "NOFX"
  - "NURSE WITH WOUND"
  - "ODDSAC"
  - "OF MONTREAL"
  - "OFF!"
  - "OHGR"
  - "OM"
  - "OONA"
  - "OPETH"
  - "OTTMAR LIEBERT"
  - "OURS"
  - "OUTSIDE LANDS MUSIC & ARTS FESTIVAL"
  - "PATRICK WATSON"
  - "PATRICK WOLF"
  - "PAUL MCCARTNEY"
  - "PEELANDER-Z"
  - "PEEPING TOM"
  - "PETER HOOK & THE LIGHT"
  - "PHISH"
  - "PIERCED ARROWS"
  - "PINK MARTINI"
  - "PITBULL DAYCARE"
  - "PIXIES"
  - "PLACEBO"
  - "POMPLAMOOSE"
  - "PORCUPINE TREE"
  - "PRIMUS"
  - "PRINCE"
  - "PSY"
  - "PUBLIC IMAGE LTD"
  - "PUBLIC SERVICE BROADCASTING"
  - "PUSCIFER"
  - "QUEENS OF THE STONE AGE"
  - "QUICKSAND"
  - "RADIOHEAD"
  - "RAILROAD REVIVAL"
  - "RAMMSTEIN"
  - "RANCID / COCK SPARRER"
  - "RATATAT"
  - "RED BARAAT"
  - "RED ELVISES"
  - "REEL BIG FISH"
  - "REFUSED"
  - "REGGIE WATTS"
  - "RHAPSODY OF FIRE"
  - "RICHARD CHEESE"
  - "ROB ZOMBIE"
  - "RODRIGO Y GABRIELA"
  - "ROGER WATERS"
  - "RON WHITE"
  - "ROYAL THUNDER"
  - "SABATON"
  - "SAUL WILLIAMS"
  - "SAVAGES"
  - "SCISSOR SISTERS"
  - "SEAL"
  - "SECRET CHIEFS 3"
  - "SF SKETCHFEST"
  - "SHADOWS FALL"
  - "SHE WANTS REVENGE"
  - "SHPONGLE"
  - "SIGUR RÓS"
  - "SILVERCHAIR"
  - "SKINNY PUPPY"
  - "SLEATER-KINNEY"
  - "SLEEP"
  - "SNOW PATROL"
  - "SOCIAL DISTORTION"
  - "SOILWORK"
  - "SONATA ARCTICA"
  - "SONIC YOUTH"
  - "SOUNDGARDEN"
  - "SPARKS"
  - "SPARTA"
  - "SPOEK MATHAMBO"
  - "SPOON"
  - "STEEL PANTHER"
  - "STEVEN WILSON"
  - "STONE TEMPLE PILOTS"
  - "STRAPPING YOUNG LAD"
  - "STRAWBERRY GIRLS"
  - "STS9"
  - "SUFJAN STEVENS"
  - "SUNN O)))"
  - "SWANS"
  - "TEMPOSHARK"
  - "TENACIOUS D"
  - "TERA MELOS"
  - "THAT 1 GUY AND THE MAGIC PIPE"
  - "THE ADICTS"
  - "THE AUSTRALIAN PINK FLOYD SHOW"
  - "THE AVENGERS"
  - "THE BOUNCING SOULS"
  - "THE CHEMICAL BROTHERS"
  - "THE CRYSTAL METHOD"
  - "THE DARKNESS"
  - "THE DEAD KENNY G'S (SKERIK + JAY LANE OF PRIMUS)"
  - "THE DEAD MILKMEN"
  - "THE DECEMBERISTS"
  - "THE DREAMING (STABBING WESTWARD)"
  - "THE DRESDEN DOLLS"
  - "THE FAINT"
  - "THE FEROCIOUS FEW"
  - "THE FIERY FURNACES"
  - "THE FLAMING LIPS"
  - "THE FUXEDOS"
  - "THE GLITCH MOB"
  - "THE JANE AUSTEN ARGUMENT"
  - "THE JESUS AND MARY CHAIN"
  - "THE JON SPENCER BLUES EXPLOSION"
  - "THE JOY FORMIDABLE"
  - "THE LEGENDARY PINK DOTS"
  - "THE MAGNETIC FIELDS"
  - "THE MARS VOLTA"
  - "THE MOODY BLUES"
  - "THE MUMLERS"
  - "THE NEW TRUST"
  - "THE POLYPHONIC SPREE"
  - "THE PRESIDENTS OF THE UNITED STATES OF AMERICA"
  - "THE PRODIGY"
  - "THE PROTOMEN"
  - "THE REAL MCKENZIES"
  - "THE RESIDENTS"
  - "THE SHINS"
  - "THE SILENT COMEDY"
  - "THE SMASHING PUMPKINS"
  - "THE SOFT MOON"
  - "THE STONE FOXES"
  - "THE SWELL SEASON"
  - "THE WAILERS"
  - "THE WORLD/INFERNO FRIENDSHIP SOCIETY"
  - "THEM CROOKED VULTURES"
  - "THERION"
  - "THEY MIGHT BE GIANTS"
  - "THROBBING GRISTLE"
  - "TITUS ANDRONICUS"
  - "TOM MORELLO (RAGE AGAINST THE MACHINE): THE NIGHTWATCHMAN"
  - "TOOL"
  - "TORI AMOS"
  - "TRANS-SIBERIAN ORCHESTRA"
  - "TREASURE ISLAND MUSIC FESTIVAL"
  - "TREY ANASTASIO"
  - "TUNE-YARDS"
  - "TV ON THE RADIO"
  - "UNDERCOVER PRESENTS"
  - "VAST"
  - "VERMILLION LIES"
  - "VIDEO GAMES LIVE"
  - "VNV NATION"
  - "VOLTAIRE"
  - "WALK OFF THE EARTH"
  - "WEEN"
  - "WILCO"
  - "WOODHANDS"
  - "X"
  - "X JAPAN"
  - "YANN TIERSEN"
  - "YEAH YEAH YEAHS"
  - "YES"
  - "YO LA TENGO"
  - "YOKO ONO & PLASTIC ONO BAND"
